### ISSUE TITLE
API for fast way not working

### ISSUE THREAD

**Issue by javierpose** [nnngrach/strava_auto_auth#2]

**Comment by peter-alexander** [comment]
Doesn't work for me too.

**Comment by HarelM** [comment]
I'm getting a `net::ERR_TUNNEL_CONNECTION_FAILED` when trying to use any of the links provided in the readme.

**Comment by zstadler** [comment]
It seems like there was a change in the API recently. Please check the example links in the [README](https://github.com/nnngrach/strava_auto_auth/blob/master/README.md#api-for-fast-way) file. They work for me.

**Comment by HarelM** [comment]
Company proxy error, removing my comments...

**Comment by javierpose** [comment]
The new urls work perfectly. Thanks
